"""empty message

Revision ID: 890ae7113b4d
Revises: 351cacbee975
Create Date: 2018-03-18 17:32:01.254155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '890ae7113b4d'
down_revision = '351cacbee975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
